version: '3.1'
services:
    nginx:
        image: mynginx
        container_name: nginx
        depends_on:
            - flask
        networks:
            - my-network
        ports:
            - 80:80
    flask:
        image: myflask
        container_name: flask
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000

networks:
    my-network:

